### ISSUE TITLE
Use java.net.URL for MblUrlRecognizer.java instead of regex.Pattern

### ISSUE THREAD

**Issue by georgeOsdDev** [datdojp/mobilib#1]
MblUrlRecognizer recognise invalid url like

```
https://:::::::::
```

http://tools.ietf.org/html/rfc1738
http://stackoverflow.com/questions/285619/how-to-detect-the-presence-of-url-in-a-string

**Comment by georgeOsdDev** [comment]
`java.net.URL` also recognise invalide url.
Can we use [android.util.Patterns.WEB_URL](http://developer.android.com/reference/android/util/Patterns.html#WEB_URL) instead?

**Comment by datdojp** [comment]
Thanks for reporting this issue.
Fixed at 85989cfc30c23379084304b69ab16ca924b06041
